// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by scripts/generate-package.sh — do not edit manually.
// Tag: firebase-12.8.0-googlesignin-7.0.0

let tag = "firebase-12.8.0-googlesignin-7.0.0"
let baseURL = "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/\(tag)"

let package = Package(
    name: "firebase-mac-xcframework",
    platforms: [.macOS(.v10_15)],
    products: [
        .library(name: "FirebaseCore", targets: ["FirebaseCoreTarget"]),
        .library(name: "FirebaseAuth", targets: ["FirebaseAuthTarget"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignInTarget"]),
    ],
    targets: [
        // -- Wrapper targets (SPM requires at least one source file per target) --
        .target(
            name: "FirebaseCoreTarget",
            dependencies: [
                "FirebaseCore", "FirebaseCoreInternal",
                "GoogleUtilities", "FBLPromises", "nanopb",
            ],
            path: "Sources/FirebaseCore"
        ),
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "FirebaseCoreTarget",
                "FirebaseAuth", "FirebaseCoreExtension", "FirebaseInstallations",
                "FirebaseAppCheckInterop", "FirebaseAuthInterop", "GTMSessionFetcher",
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "GoogleSignIn", "AppAuthCore", "GTMAppAuth", "GTMSessionFetcher",
            ],
            path: "Sources/GoogleSignIn"
        ),

        // -- Binary targets (checksums updated by CI via generate-package.sh) --
        .binaryTarget(
            name: "FirebaseCore",
            url: "\(baseURL)/FirebaseCore.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "\(baseURL)/FirebaseCoreInternal.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "\(baseURL)/FirebaseCoreExtension.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "\(baseURL)/FirebaseInstallations.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseAuth",
            url: "\(baseURL)/FirebaseAuth.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseAppCheckInterop",
            url: "\(baseURL)/FirebaseAppCheckInterop.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FirebaseAuthInterop",
            url: "\(baseURL)/FirebaseAuthInterop.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "\(baseURL)/GoogleUtilities.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "FBLPromises",
            url: "\(baseURL)/FBLPromises.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "\(baseURL)/nanopb.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "GoogleSignIn",
            url: "\(baseURL)/GoogleSignIn.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "AppAuthCore",
            url: "\(baseURL)/AppAuthCore.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "GTMAppAuth",
            url: "\(baseURL)/GTMAppAuth.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
        .binaryTarget(
            name: "GTMSessionFetcher",
            url: "\(baseURL)/GTMSessionFetcher.xcframework.zip",
            checksum: "PLACEHOLDER"
        ),
    ]
)
