// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by scripts/generate-package.sh — do not edit manually.
// Tag: firebase-12.8.0-googlesignin-7.0.0-r2

let package = Package(
    name: "firebase-mac-xcframework",
    platforms: [.macOS(.v10_15)],
    products: [
        .library(name: "FirebaseAuth", targets: ["FirebaseAuthTarget"]),
        .library(name: "FirebaseCore", targets: ["FirebaseCoreTarget"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignInTarget"]),
    ],
    targets: [
        // -- Wrapper targets (SPM requires at least one source file per target) --
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "FirebaseCoreTarget",
                "FirebaseAuth",
                "FirebaseCoreExtension",
                "FirebaseInstallations",
                "FirebaseAppCheckInterop",
                "FirebaseAuthInterop",
                "GTMSessionFetcher",
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "FirebaseCoreTarget",
            dependencies: [
                "FirebaseCore",
                "FirebaseCoreInternal",
                "GoogleUtilities",
                "FBLPromises",
                "nanopb",
            ],
            path: "Sources/FirebaseCore"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "GoogleSignIn",
                "AppAuthCore",
                "GTMAppAuth",
                "GTMSessionFetcher",
            ],
            path: "Sources/GoogleSignIn"
        ),

        // -- Binary targets --
        .binaryTarget(
            name: "AppAuthCore",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/AppAuthCore.xcframework.zip",
            checksum: "d2af3ee0add0cfe1f8c781ff058dc10ec4c6c73097a7c6be897939c5f61a37b9"
        ),
        .binaryTarget(
            name: "FBLPromises",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FBLPromises.xcframework.zip",
            checksum: "8093831dbf6629c34dc36f6997fdf046122350a82ead88828790b27554c4bfe9"
        ),
        .binaryTarget(
            name: "FirebaseAppCheckInterop",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseAppCheckInterop.xcframework.zip",
            checksum: "389152341fe48206869ed9208c5889836e9aabdbb1a6b8b89e53a0eaa5b87686"
        ),
        .binaryTarget(
            name: "FirebaseAuth",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseAuth.xcframework.zip",
            checksum: "b698c186b727b4cf616a042da7f895d4ee06f429b17ad8bbac8f8653b216e773"
        ),
        .binaryTarget(
            name: "FirebaseAuthInterop",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseAuthInterop.xcframework.zip",
            checksum: "a82101b90d0bb4109e4fb016be04d52efba215b41bcffb7cca4e51077e75cc16"
        ),
        .binaryTarget(
            name: "FirebaseCore",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseCore.xcframework.zip",
            checksum: "26d2eb3eeeeba2862d90dd56eb0c59a7e96103e774c1c7ae645987ad7ca41dc1"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseCoreExtension.xcframework.zip",
            checksum: "6e4329653184fb0f1631df85f0547efb4554c6098064db418e2c983f71c3fe83"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseCoreInternal.xcframework.zip",
            checksum: "3bfc3483b2514fb489cb8745080a9c990c48ba7c519c7b5ff87d84824a7dae54"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/FirebaseInstallations.xcframework.zip",
            checksum: "fc7bc7172effb52158d72ba5dce5ea7dbc33963a0cc2790de2312700314a288c"
        ),
        .binaryTarget(
            name: "GoogleSignIn",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/GoogleSignIn.xcframework.zip",
            checksum: "8ac6bb8adb30b797ae7083171ae94d9392236878e1e3c03febe8a34bb1e679cd"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/GoogleUtilities.xcframework.zip",
            checksum: "37ce8c4698819a751f2ca7691c93a783233a91463750a594885d09a4c7f09508"
        ),
        .binaryTarget(
            name: "GTMAppAuth",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/GTMAppAuth.xcframework.zip",
            checksum: "fec3b8695e5c7fde4bed57ac236705a6a67f74715f3b8ce89116b6564f35ad6c"
        ),
        .binaryTarget(
            name: "GTMSessionFetcher",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/GTMSessionFetcher.xcframework.zip",
            checksum: "81a7aecae96ed2dc62b12a089054f83fe6346affe2bc7215947f8f4c8f0cbcd5"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0-r2/nanopb.xcframework.zip",
            checksum: "8b6e0aa0c93488edbc94ca08f03fae003c88331a1e837acd4f9f96f2c59af9a5"
        ),
    ]
)
