// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by scripts/generate-package.sh — do not edit manually.
// Tag: firebase-12.8.0-googlesignin-7.0.0

let package = Package(
    name: "firebase-mac-xcframework",
    platforms: [.macOS(.v10_15)],
    products: [
        .library(name: "FirebaseAuth", targets: ["FirebaseAuthTarget"]),
        .library(name: "FirebaseCore", targets: ["FirebaseCoreTarget"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignInTarget"]),
    ],
    targets: [
        // -- Wrapper targets (SPM requires at least one source file per target) --
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "FirebaseCoreTarget",
                "FirebaseAuth",
                "FirebaseCoreExtension",
                "FirebaseInstallations",
                "FirebaseAppCheckInterop",
                "FirebaseAuthInterop",
                "GTMSessionFetcher",
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "FirebaseCoreTarget",
            dependencies: [
                "FirebaseCore",
                "FirebaseCoreInternal",
                "GoogleUtilities",
                "FBLPromises",
                "nanopb",
            ],
            path: "Sources/FirebaseCore"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "GoogleSignIn",
                "AppAuthCore",
                "GTMAppAuth",
                "GTMSessionFetcher",
            ],
            path: "Sources/GoogleSignIn"
        ),

        // -- Binary targets --
        .binaryTarget(
            name: "AppAuthCore",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/AppAuthCore.xcframework.zip",
            checksum: "91166e45e89685c58bd4ebfa841dadd3e2647e41c5958c48b7215dd9ff955755"
        ),
        .binaryTarget(
            name: "FBLPromises",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FBLPromises.xcframework.zip",
            checksum: "5edfabe6a56136dafb99fd6802f9b6cf91d66ac3dcfc0d05b2347b8a9ef18ee2"
        ),
        .binaryTarget(
            name: "FirebaseAppCheckInterop",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseAppCheckInterop.xcframework.zip",
            checksum: "00b3232cc1e395ccef22427964581dfd211a67f967897ce5104c253c8fa11260"
        ),
        .binaryTarget(
            name: "FirebaseAuth",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseAuth.xcframework.zip",
            checksum: "ff674ba9c2c15330cccf75362aeb2e6073d99ef8b56dca36c04a8ad07f41f6c3"
        ),
        .binaryTarget(
            name: "FirebaseAuthInterop",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseAuthInterop.xcframework.zip",
            checksum: "0b9c5cc4cd7fa34b66060b096147fc97e5f1eab190341cbf53b1d75183c7f005"
        ),
        .binaryTarget(
            name: "FirebaseCore",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseCore.xcframework.zip",
            checksum: "da4d63b9e877e1ffb85139ec8ad6a60a7bffb5e981090cfefe2c58ebcdfc8356"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseCoreExtension.xcframework.zip",
            checksum: "b779f5b79c4290f6801c6500d7ee592cd576f0bc1e5c674ad86bf3d4c22713ed"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseCoreInternal.xcframework.zip",
            checksum: "89a197e92398beb3e5d2b8f833c6fc50b967a15ae8a6bfb3b757e015b23c0387"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/FirebaseInstallations.xcframework.zip",
            checksum: "7cc3bfd029096c3a39450ca99192f8b80bc82eda06de462f881412e185b4f50f"
        ),
        .binaryTarget(
            name: "GTMAppAuth",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/GTMAppAuth.xcframework.zip",
            checksum: "b8d55cc07eb2b1cabf43ede545cd15beac0ed608f6cc2617021d50c21408edb7"
        ),
        .binaryTarget(
            name: "GTMSessionFetcher",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/GTMSessionFetcher.xcframework.zip",
            checksum: "2ae6e855d6d08e44106ee86022816994e617a10e20488c995e9ac83204287a28"
        ),
        .binaryTarget(
            name: "GoogleSignIn",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/GoogleSignIn.xcframework.zip",
            checksum: "b99abca79ce3803405a9d652fc72969daeaf5009f8734cebce94eba1852869e6"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/GoogleUtilities.xcframework.zip",
            checksum: "9118a82eb861776ec6c91f01e862d891f38285eba8458e09dd34ee008a225049"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/firebase-12.8.0-googlesignin-7.0.0/nanopb.xcframework.zip",
            checksum: "ed5cc69e8f5cde8ca5cb6c5fa542e9356f07ad5e2d3ca8c156e2f8b79d1da2e4"
        ),
    ]
)
