#!/bin/bash
set -euo pipefail

# =============================================================================
# Generate Package.swift from checksums.txt
#
# Usage:
#   TAG=firebase-12.8.0-googlesignin-7.0.0 bash scripts/generate-package.sh
#
# Reads checksums.txt (produced by build.sh) and writes Package.swift with
# .binaryTarget(url:checksum:) entries pointing to the GitHub Release assets.
# =============================================================================

TAG="${TAG:?TAG is required (e.g. firebase-12.8.0-googlesignin-7.0.0)}"
CHECKSUMS_FILE="${CHECKSUMS_FILE:-/tmp/firebase-mac-build/zips/checksums.txt}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="${REPO_ROOT}/Package.swift"
BASE_URL="https://github.com/SpeechifyInc/firebase-mac-xcframework/releases/download/${TAG}"

if [ ! -f "${CHECKSUMS_FILE}" ]; then
  echo "ERROR: checksums.txt not found at ${CHECKSUMS_FILE}"
  echo "Run build.sh first to generate it."
  exit 1
fi

# Helper: look up checksum for a given xcframework name from checksums.txt
get_checksum() {
  local zip_name="$1.xcframework.zip"
  grep "^${zip_name} " "${CHECKSUMS_FILE}" | awk '{print $2}'
}

# Build the binary targets block
binary_targets=""
XCFRAMEWORK_NAMES=(
  FirebaseCore FirebaseCoreInternal FirebaseCoreExtension FirebaseInstallations
  FirebaseAuth FirebaseAppCheckInterop FirebaseAuthInterop GoogleUtilities
  FBLPromises nanopb GoogleSignIn AppAuthCore GTMAppAuth GTMSessionFetcher
)

for name in "${XCFRAMEWORK_NAMES[@]}"; do
  checksum=$(get_checksum "${name}")
  if [ -z "${checksum}" ]; then
    echo "WARNING: No checksum found for ${name}.xcframework.zip"
    continue
  fi
  binary_targets+="        .binaryTarget(
            name: \"${name}\",
            url: \"${BASE_URL}/${name}.xcframework.zip\",
            checksum: \"${checksum}\"
        ),
"
done

cat > "${OUTPUT}" << PKGEOF
// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by scripts/generate-package.sh — do not edit manually.
// Tag: ${TAG}

let package = Package(
    name: "firebase-mac-xcframework",
    platforms: [.macOS(.v10_15)],
    products: [
        .library(name: "FirebaseCore", targets: ["FirebaseCoreTarget"]),
        .library(name: "FirebaseAuth", targets: ["FirebaseAuthTarget"]),
        .library(name: "GoogleSignIn", targets: ["GoogleSignInTarget"]),
    ],
    targets: [
        // -- Wrapper targets (SPM requires at least one source file per target) --
        .target(
            name: "FirebaseCoreTarget",
            dependencies: [
                "FirebaseCore", "FirebaseCoreInternal",
                "GoogleUtilities", "FBLPromises", "nanopb",
            ],
            path: "Sources/FirebaseCore"
        ),
        .target(
            name: "FirebaseAuthTarget",
            dependencies: [
                "FirebaseCoreTarget",
                "FirebaseAuth", "FirebaseCoreExtension", "FirebaseInstallations",
                "FirebaseAppCheckInterop", "FirebaseAuthInterop", "GTMSessionFetcher",
            ],
            path: "Sources/FirebaseAuth"
        ),
        .target(
            name: "GoogleSignInTarget",
            dependencies: [
                "GoogleSignIn", "AppAuthCore", "GTMAppAuth", "GTMSessionFetcher",
            ],
            path: "Sources/GoogleSignIn"
        ),

        // -- Binary targets --
${binary_targets}    ]
)
PKGEOF

echo "Generated ${OUTPUT}"
echo "Tag: ${TAG}"
